server:
  port: 8004

spring:
  application:
    name: my-hotel-api
    description: my hotel api
    version : @project.version@

  datasource:
    url: jdbc:mysql://localhost:3306/myhotel
    username : root
    password : root
  jpa:
    hibernate :
      ddl-auto : create
      show-sql : true


zuul:
  prefix: /api
  routes:
    guest-service:
      path : /guest-service/**
      url : http://localhost:8001
    hotel-service:
      path: /hotel-service/**
      url: http://localhost:8002
    reservation-service:
      path: /reservation-service/**
      url: http://localhost:8003
  sensitive-headers: Cookie,Set-Cookie

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8383/eureka/
  instance:
    hostname: localhost